AniTrend/anitrend-app

app/src/main/java/com/mxt/anitrend/base/custom/view/container/CardViewBase.java, app/src/main/java/com/mxt/anitrend/base/custom/view/container/NotificationCardView.java, app/src/main/res/drawable/ic_notification_border.xml, app/src/main/res/layout/adapter_notification.xml
=> Change Notification Unread Indicator

.travis.yml
=> Update platform version to match build.gradle

app/src/main/java/com/mxt/anitrend/App.java, app/src/main/java/com/mxt/anitrend/base/custom/activity/ActivityBase.java, app/src/main/java/com/mxt/anitrend/util/ApplicationPref.java, app/src/main/java/com/mxt/anitrend/util/LocaleHelper.java, app/src/main/java/com/mxt/anitrend/view/activity/base/SettingsActivity.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/pref_general.xml
Added the ability to change the app's language but the user. It Requires the app to be restarted and cleared from the memory.
closes #66
=> Added Option To Change Application Language

app/src/main/java/com/mxt/anitrend/view/activity/base/AppCompatPreferenceActivity.java, app/src/main/res/values-v21/style.xml, app/src/main/res/values-v23/style.xml, app/src/main/res/values-v26/style.xml, app/src/main/res/values/color.xml, app/src/main/res/values/style.xml
Hopefully I didn't miss anything. 😄
=> Fixed Some Thematic Issues.

app/src/main/res/values/style.xml
This patches my previous PR and fixes the Dark theme for lower API levels.
=> Dark Theme Overflow-Popup Patch

app/src/main/res/values/strings.xml
Better wording for Black theme toggle option in Settings -> Customize
Better and clearer wording, and fixing grammar
Ran the app to see if text changed accordingly
=> Change Black Theme Toggle Description

app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
Added support for the Swedish Language. The purpose is to expand on the application usability with a help of more languages. I have read all the rules and guidelines and followed the standards based on the description.
=> Added Swedish Language

app/src/main/java/com/mxt/anitrend/view/activity/base/ImagePreviewActivity.java, app/src/main/res/layout/activity_image_preview.xml, app/src/main/res/menu/image_preview_menu.xml, app/src/main/res/values/color.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/style.xml
This PR add toolbar that allow the user to share, download, and/or open in browser the selected current image in `ImagePreviewActivity`.
=> Add a Toolbar to the ImagePreviewActivity

app/src/main/AndroidManifest.xml, app/src/main/java/com/mxt/anitrend/view/activity/base/ReportActivity.java, app/src/main/java/com/mxt/anitrend/view/activity/index/MainActivity.java, app/src/main/res/drawable/ic_bug_report_grey_600_24dp.xml, app/src/main/res/layout/activity_report.xml, app/src/main/res/layout/activity_report_test.xml, app/src/main/res/menu/main_menu.xml, app/src/main/res/values/strings.xml
Adds an option to access `logcat` logs of AniTrend as well as an option to save it in the Downloads directory for sharing. 
Easier to report non-crashing bugs without the need of root or a computer.  
Quickly skimmed the log outputted to confirm it's correctly showing up
=> Add Option to Access Logs

app/src/main/assets/graphql/Media/Query/MediaOverview.graphql, app/src/main/java/com/mxt/anitrend/presenter/fragment/MediaPresenter.java
Previously the media duration was hard coded to TBA.
Now the duration is accurate.
Someone asked about it so I fixed it.
I tested a few titles and the duration values are accurate. If no duration is present, "TBA" will be displayed.
**IMPORTANT**: By submitting a patch, …
=> Added duration to media items

app/src/main/assets/graphql/queries/media/MediaBrowse.graphql, app/src/main/assets/graphql/queries/media/MediaSearch.graphql, app/src/main/assets/graphql/queries/media/detail/MediaBase.graphql, app/src/main/assets/graphql/queries/media/detail/MediaCharacters.graphql, app/src/main/assets/graphql/queries/media/detail/MediaEpisodes.graphql, app/src/main/assets/graphql/queries/media/detail/MediaOverview.graphql, app/src/main/assets/graphql/queries/media/detail/MediaRelations.graphql, app/src/main/assets/graphql/queries/media/detail/MediaStaff.graphql, app/src/main/assets/graphql/queries/media/detail/MediaStats.graphql, app/src/main/assets/graphql/queries/recommendation/RecommendationMedia.graphql, app/src/main/java/com/mxt/anitrend/util/graphql/GraphUtil.kt
The way I initially implemented the option makes it so that when enabling the option, anilist will only return nsfw content. this changes that so it shows everything when the option is enabled, and only sfw when the option is disabled
=> Fix enabling NSFW content showing only NSFW content and excluding SFW content

app/src/main/java/com/mxt/anitrend/base/custom/view/widget/AboutPanelWidget.java
This fixes the followers counter in the user about section being updated when following/unfollowing someone in the BottomSheet
Yes, in my phone
=>  Fix the followers counter being updated instead of the followering counter when (un)following someone

app/src/github/res/xml/root_preferences.xml
Fix missing "List View Style" setting in the GitHub flavour 
=> Fix missing list view style setting in the github flavour 

app/src/main/AndroidManifest.xml
On recent AOSP versions, you need to have this permission granted
otherwise, nothing happens when you click DownloaderService's
notification or attempt to manually install downloaded apk from
AOSP `Files` app.
On AOSP 11 it was impossible to install github apk updates …
=> Grant android.permission.REQUEST_INSTALL_PACKAGES

app/src/main/res/values-ar/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
Turns out that unescaped quotes get totally stripped out
during compilation which in the end led to a broken link
in "Update AniTrend?" dialog.
I noticed that there was a broken link in Update AniTrend so I tried to find out why and after printing HTML content passed to …
=> Escape quotes when using HTML inside CDATA strings

app/src/main/res/values-fr/strings.xml
Fix missing quote escape in French string translation.
n/a
n/a
n/a
=> Fix missing quote escape in French string translation

.github/workflows/android-build.yaml
Added a test to the github actions workflow that build the app automatically on tag push.
This has been tested on a fork until everything worked, then created a new branch with all the changes combined.
I used Github Actions and CodeSpaces.
**IMPORTANT**: By submitting a …
=> Add test to android build workflow

app/src/main/java/com/mxt/anitrend/adapter/recycler/index/MediaListAdapter.kt, app/src/main/res/values/dimens.xml
This PR fixes the Airing Series Compact card title getting covered by the AutoIncrement widget in the single column compact list view, by automatically adding a margin of `36dp` at the end when in single column list view.
Right now, in the single column list view, is an …
=> Fix Airing Series Compact card title

app/src/main/assets/graphql/fragments/user/UserStatisticsFragment.graphql, app/src/main/java/com/mxt/anitrend/base/custom/view/widget/ProfileStatsWidget.java
This PR fixes 2 issues:
1. The issue introduced by 469f656 where the commented out code gets inlined, which in turn makes the rest of the query "commented out", and causes an "unexpected EOF" issue.
2. Makes it possible to go to a user's anime/manga list even when the …
=> Fix profile loading issue and Allow opening the user's list when the overview screen doesn't load

app/src/main/java/com/mxt/anitrend/model/entity/anilist/meta/TitleBase.java
Apparently some characters only have the last name.
Characters without first name would use "null {lastname}" instead of "{lastname}".
Some characters don't have a first name.
Search for "Nyuusaskin" character.
**IMPORTANT**: By submitting a patch, you agree to allow the …
=> getFullName: Discard first name if null

app/src/main/assets/graphql/fragments/character/CharacterNameFragment.graphql
We need to capture `alternative` as we are trying to display it.
This fixes missing alternative names for characters that happen to have those.
Open "Illyasviel von Einzbern" character page, observe that now "Alternative Names" are filled.
**IMPORTANT**: By submitting a …
=> Add `alternative` to CharacterNameFragment

app/src/main/java/com/mxt/anitrend/model/entity/anilist/meta/TitleBase.java
This makes character screen show "No content available" when
given character doesn't have any alternative names.
On characters without any alternative names it'd show empty textview rather than one that says "No content available".
Open "Emilia" …
=> getAlternativeFormatted: Don't be afraid to return null

app/src/main/java/com/mxt/anitrend/util/collection/GroupingUtil.kt
Just a minor code style/perf improvement.
This change was suggested in #403.
Went through various fragments that should be using these functions.
n/a
owners to license your work under the terms of the …
=> GroupingUtil: Simplify the way we obtain the entity map list

app/src/main/java/com/mxt/anitrend/util/IntentBundleUtil.kt, app/src/main/java/com/mxt/anitrend/view/activity/detail/ProfileActivity.java
This adds support for /user/{username}/animelist and /user/{username}/mangalist deep links.
This lets us open someone's anime/manga via URL.
I tested it by trying to open the following URLs:
* https://anilist.co/user/AniTrend
* https://anilist.co/user/AniTrend/
* …
=> Add bare minimum /user/{animelist,mangalist} deep link support

README.md
Waffle.io died, link to /issues page instead.
n/a
n/a
=> README: Replace dead waffle.io link with a link to /issues page

app/src/main/java/com/mxt/anitrend/analytics/AnalyticsLogging.kt
When using a build without Firebase setup, we'd be getting unnecessary log spam when doing certain actions in the app.
Open app, then close and resume it, observe that following log messages are gone:
```
05-06 22:21:58.336 12272 12272 W System.err: …
```
=> Nullify all Firebase calls when FirebaseApp is not initialized

app/src/app/res/xml/root_preferences.xml, app/src/github/res/xml/root_preferences.xml, app/src/main/java/com/mxt/anitrend/view/activity/base/SettingsActivity.kt, app/src/main/res/values/preference_keys.xml
Privacy settings don't do anything on builds without google-services.json.
Tested builds with and without google-services.json file.
n/a
owners to license your work under the terms of …
=> Hide privacy category if Firebase is not initialized

app/schema.graphql
Just regenerated schema.json using `JS GraphQL` plugin.
Our schema was not only outdated but also edited manually in a couple of places.
Opened the app and went through various pages.
n/a
owners to …
=> Regenerate schema.graphql

app/src/main/java/com/mxt/anitrend/base/custom/activity/ActivityBase.java, app/src/main/java/com/mxt/anitrend/view/activity/detail/NotificationActivity.java
When NotificationActivity is launched from notification going back would close the app. This changes the behavior in a way that makes it open MainActivity on back pressed instead.
Open notification or notifications list from the app and then go back by …
=> Go back to from NotificationActivity to MainActivity if launched directly

app/src/main/java/com/mxt/anitrend/view/activity/index/MainActivity.kt
Previously we only updated the presenter current user on logging in, this makes it do that on MainActivity create / resume.
Open app, change avatar/cover photo, close and reopen app.
n/a
**IMPORTANT**: By submitting a patch, you agree to allow the …
=> Sync local current user data on MainActivity create / resume

app/src/main/java/com/mxt/anitrend/view/fragment/detail/NotificationFragment.kt
Noticed that there was a code that was dispatching notifications on NotificationFragment load but it was outdated so I updated it.
Uncomment, compile, open `Notification Hub`.
n/a …
=> Update notification testing code

app/src/main/java/com/mxt/anitrend/base/custom/async/WebTokenRequest.java, app/src/main/java/com/mxt/anitrend/receiver/ClearNotifications.kt, app/src/main/java/com/mxt/anitrend/util/KeyUtil.java, app/src/main/java/com/mxt/anitrend/util/NotificationUtil.kt, app/src/main/java/com/mxt/anitrend/util/Settings.kt, app/src/main/java/com/mxt/anitrend/view/fragment/detail/NotificationFragment.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
This change stores the top notification id in settings and uses it to prevent sending out previously dismissed notifications.
We are also renaming the old dismiss setting because it now just marks notifications as read on AniList.
* Receive a …
=> Ignore dismissed notifications across unread notification syncs

app/src/main/java/com/mxt/anitrend/view/activity/base/LoggingActivity.kt
When log file has many lines (in my case almost 8000 lines), logging activity starts taking a long time to load lines.
Using fromHTML() + toHTML() makes it load much faster.
Noticed logging activity froze on my phone so I thought of using HTML and it worked.
Make sure …
=> Improve LoggingActivity performance

app/src/main/AndroidManifest.xml, app/src/main/java/com/mxt/anitrend/view/activity/base/LoggingActivity.kt, app/src/main/res/xml/file_provider_paths.xml
Android Binder is not prepared for us trying to share large text data thus it crashes when we attempt to do so.
Noticed that share kept crashing on my phone, this change fixed it.
Prepare long `/storage/emulated/0/Android/data/com.mxt.anitrend/files/logs/com.mxt.anitrend. …
=> Share logs as files rather than text

app/src/main/assets/graphql/queries/staff/detail/StaffCharacters.graphql, app/src/main/assets/graphql/queries/staff/detail/StaffMedia.graphql, app/src/main/assets/graphql/queries/staff/detail/StaffRoles.graphql, app/src/main/java/com/mxt/anitrend/view/activity/detail/StaffActivity.java, app/src/main/java/com/mxt/anitrend/view/fragment/group/MediaAnimeRoleFragment.java, app/src/main/java/com/mxt/anitrend/view/fragment/group/MediaFormatFragment.java, app/src/main/java/com/mxt/anitrend/view/fragment/group/MediaStaffRoleFragment.java, app/src/main/res/menu/staff_menu.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
This change adds 'onList' filtering for Staff{Characters,Media,Roles}.
AniList webpage allows doing that, I don't see why we shouldn't ^.^
Open any staff page then select "On My List" from menu.
owners …
=> Add 'onList' filtering for Staff{Characters,Media,Roles}

app/src/main/java/com/mxt/anitrend/view/sheet/BottomReviewReader.java, app/src/main/res/layout/custom_review_template.xml
This basically mimics behavior present for user statuses.
Open bottom sheet review, click on user avatar.
n/a …
=> Open user profile on bottom sheet review avatar click

app/src/main/assets/graphql/queries/media/detail/MediaCharacters.graphql
This makes us use the same sorting as the website.
Discord user noticed that sorting didn't match the website so I decided to look at it.
Open media characters page in browser and app, compare them.
n/a …
=> Sort MediaCharacters by [ROLE, RELEVANCE, ID]

app/src/main/java/com/mxt/anitrend/model/entity/group/RecyclerHeaderItem.java, app/src/main/java/com/mxt/anitrend/util/collection/GroupingUtil.kt
This makes TBA be displayed on top of staff roles.
For that we also need to allow disabling unnecessary tile
capitalization as 'Tba' looks kinda out of place.
Previously TBA would be displayed as "0", this makes it be listed as "TBA" instead.
n/a
Open …
=> Add special handling for TBA in groupCharactersByYear()

app/src/main/java/com/mxt/anitrend/view/activity/detail/StaffActivity.java
For some odd reason, reusing adapter results in weirdly looking role fragments after enabling onList.
n/a
Open https://anilist.co/staff/132768/Ikumi-Hasegawa and enable onList, notice that there are no empty spots anymore.
**IMPORTANT**: By submitting a patch, you agree …
=> Don't reuse ViewPager adapter during StaffActivity::reloadViewPager()

app/src/main/java/com/mxt/anitrend/view/activity/detail/StaffActivity.java, app/src/main/java/com/mxt/anitrend/view/fragment/group/MediaAnimeRoleFragment.java, app/src/main/java/com/mxt/anitrend/view/fragment/group/MediaFormatFragment.java, app/src/main/java/com/mxt/anitrend/view/fragment/group/MediaStaffRoleFragment.java
arg_onList accepts null, false, or true and passing false by default
makes some entries invisible when logged in.
arg_onList accepts null, false, or true and passing false by default makes some entries invisible when logged in.
n/a
Open …
=> Pass Boolean object as arg_onList

app/src/main/java/com/mxt/anitrend/adapter/pager/detail/StaffPageAdapter.java, app/src/main/java/com/mxt/anitrend/base/custom/fragment/FragmentBase.java, app/src/main/java/com/mxt/anitrend/view/activity/detail/StaffActivity.java, app/src/main/res/menu/staff_menu.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values/strings.xml
This change moves onList filtering to filter style menu plus adds a way to pass 'false' instead of just null/true that #429 introduced.
n/a
Open staff profile and swipe between fragments, notice that filtering menu appears when necessary plus allows for changing onList …
=> Replace onList checkbox with tri-state selection dialog

app/src/main/java/com/mxt/anitrend/util/collection/GroupingUtil.kt
This fixes entries being shown under invalid relation types in media relations fragment.
Plus it also makes relation types ordered alphabetically while at it.
Discord user noticed that https://anilist.co/manga/65243/Haikyuu/ relations were displayed improperly, this …
=> Sort edges by relationType when grouping them

app/src/main/assets/graphql/queries/media/detail/MediaOverview.graphql, app/src/main/java/com/mxt/anitrend/util/KeyUtil.java
This change switches all MediaSource usages to version 2.
That's what the website uses after all.
Open https://anilist.co/manga/110103/Toukosan-wa-Kaji-ga-Dekinai, notice that "Series Origin" now says Doujinshi instead of Other.
n/a
**IMPORTANT**: By submitting a patch, …
=> Switch MediaSource to version 2

app/src/main/java/com/mxt/anitrend/view/activity/index/MainActivity.kt
onPostCreate() isn't called in time for configuration changes thus making the app crash due to lateInit var `menuItems` not being initialized.
Open the app and rotate the device, notice that the app doesn't crash anymore.
n/a
**IMPORTANT**: By submitting …
=> Initialize MainActivity's ViewPager / NavigationView in onCreate()

app/src/main/java/com/mxt/anitrend/model/entity/anilist/meta/FuzzyDate.java, app/src/main/java/com/mxt/anitrend/util/date/DateUtil.kt
Some shows only have a year or month+year set.
n/a
Open https://anilist.co/anime/129874/Kimetsu-no-Yaiba-Yuukakuhen/, notice that it now says "Started: 2021".
n/a
owners to license your work under the …
=> Return specialized date format when using FuzzyDate

app/src/main/res/values/string_arrays.xml
Settings ⇾ Application Language was displaying invalid titles, this change corrects that.
Open settings.
n/a …
=> Fix selected language titles array

app/src/main/java/com/mxt/anitrend/base/plugin/image/GlideImagePlugin.kt
Fixes laggy scrolling when a lot of images are visible at the same time.
This change fixes laggy scrolling when a lot of markdown images are visible at the same time.
Open https://anilist.co/activity/307951935 and scroll. Also opened random profiles to …
=> Override markdown glide image size to 720

app/src/main/assets/graphql/queries/recommendation/RecommendationMedia.graphql, app/src/main/java/com/mxt/anitrend/adapter/pager/detail/AnimePageAdapter.java, app/src/main/java/com/mxt/anitrend/adapter/pager/detail/MangaPageAdapter.java, app/src/main/java/com/mxt/anitrend/model/api/retro/anilist/MediaModel.kt, app/src/main/java/com/mxt/anitrend/model/entity/container/body/ConnectionContainer.java, app/src/main/java/com/mxt/anitrend/view/fragment/group/MediaRecommendationsFragment.java, app/src/main/res/values/string_arrays.xml, app/src/main/res/values/strings.xml
This change basically adds recommendations tab to anime/manga entries.
n/a
Open any anime/manga entry, swipe straight to recommendations tab. …
=> Add recommendations tab to anime/manga entries

app/src/main/java/com/mxt/anitrend/base/plugin/image/GlideImagePlugin.kt
```
11-29 12:44:17.389 28234 28234 E AndroidRuntime: FATAL EXCEPTION: main
11-29 12:44:17.389 28234 28234 E AndroidRuntime: Process: com.mxt.anitrend, PID: 28234
11-29 12:44:17.389 28234 28234 E AndroidRuntime: java.lang.RuntimeException: Canvas: trying to draw too …
```
=> Use fitCenter() in GlideImagePlugin

app/src/main/java/com/mxt/anitrend/view/fragment/group/MediaRecommendationsFragment.java
This change fixes a crash when displaying recommendation entries where one of them has null "mediaRecommendation".
Open https://anilist.co/manga/42854/A-Certain-Magical-Index/, see that it doesn't crash anymore.
n/a
**IMPORTANT**: By submitting a patch, …
=> Handle null mediaRecommendation entries

app/src/main/java/com/mxt/anitrend/base/plugin/image/GlideImagePlugin.kt
Fixes crash due to Preconditions.checkNotNull(url).
Made `url` null, app no longer crashed. …
=> Wrap GlideUrl object creation with runCatching { ... }.getOrNull()

app/src/main/java/com/mxt/anitrend/view/activity/detail/ProfileActivity.java
This basically copies same null checks as we had in R.id.action_message handling.
#463
n/a …
=> Null check model before attempting to share profile URL

app/src/main/java/com/mxt/anitrend/view/activity/detail/ProfileActivity.java
Fixes sharing profile URL to apps like Telegram.
Open your own profile and try to share it.
n/a …
=> Improve profile URL sharing experience

app/src/main/java/com/mxt/anitrend/view/activity/base/LoggingActivity.kt, app/src/main/java/com/mxt/anitrend/view/activity/detail/CharacterActivity.java, app/src/main/java/com/mxt/anitrend/view/activity/detail/MediaActivity.java, app/src/main/java/com/mxt/anitrend/view/activity/detail/StaffActivity.java, app/src/main/java/com/mxt/anitrend/view/activity/detail/StudioActivity.java, app/src/main/java/com/mxt/anitrend/view/activity/index/MainActivity.kt, app/src/main/java/com/mxt/anitrend/view/fragment/detail/CommentFragment.java
This lets us share links / files to apps like Telegram.
Tested share in couple activities.
n/a …
=> Use Intent.createChooser() everywhere

app/src/main/java/com/mxt/anitrend/base/custom/view/widget/ProfileStatsWidget.java
This fixes a possible NPE in onClick() when user tries to go to anime / manga list of any given user before the data has been fully loaded.
Tapped very fast on anime list when trying to open user profile.
n/a
**IMPORTANT**: By submitting a patch, you …
=> Move setClickListener(this) to updateUI() in ProfileStatsWidget

app/.meta/version.json, app/src/main/assets/changelog.md, app/src/main/java/com/mxt/anitrend/base/custom/view/widget/ProfileStatsWidget.java, app/src/main/java/com/mxt/anitrend/base/plugin/image/GlideImagePlugin.kt, app/src/main/java/com/mxt/anitrend/view/activity/base/LoggingActivity.kt, app/src/main/java/com/mxt/anitrend/view/activity/detail/CharacterActivity.java, app/src/main/java/com/mxt/anitrend/view/activity/detail/MediaActivity.java, app/src/main/java/com/mxt/anitrend/view/activity/detail/ProfileActivity.java, app/src/main/java/com/mxt/anitrend/view/activity/detail/StaffActivity.java, app/src/main/java/com/mxt/anitrend/view/activity/detail/StudioActivity.java, app/src/main/java/com/mxt/anitrend/view/activity/index/MainActivity.kt, app/src/main/java/com/mxt/anitrend/view/fragment/detail/CommentFragment.java, buildSrc/src/main/java/com/mxt/anitrend/buildsrc/common/Versions.kt
=> Release/1.9.6 ➡️ Develop

app/src/main/java/com/mxt/anitrend/base/custom/activity/ActivityBase.java
This change makes us save and restore presenter search filter whenever activity gets recreated.
Open search view in anime list, type something, then rotate the device few times. Notice that search query is no longer being ignored.
n/a
**IMPORTANT**: By …
=> Restore search query after activities are recreated

app/src/main/res/values/string_array_items.xml
=> Fix the name of the Netherlands language

app/src/main/java/com/mxt/anitrend/model/entity/base/NotificationBase.java
Some notifications, notably MEDIA_DATA_CHANGE have context that starts with a space.
Noticed that MEDIA_DATA_CHANGE notification had a space at the beginning, this fixes it.
Looked at notification hub.
n/a
**IMPORTANT**: By submitting a patch, you agree to allow the …
=> Trim context in NotificationBase

app/src/main/java/com/mxt/anitrend/adapter/recycler/detail/NotificationAdapter.kt, app/src/main/java/com/mxt/anitrend/view/fragment/detail/NotificationFragment.kt
This makes MEDIA_{DATA_CHANGE,DELETION,MERGE} notifications display properly in app.
Noticed they weren't working so I fixed them.
Open notification hub.
owners to license your work under the terms of …
=> Add suport for MEDIA_{DATA_CHANGE,DELETION,MERGE} notifications

app/src/main/res/values-v21/style.xml
This changes the navbar of the black theme to match the theme, so it's better on AMOLED devices.
Supported on API v21+, so added overrides in values-v21.
Black theme uses a white navbar. 
Tested on API 17, API 21, API 32 emulators, on physical API 31 device.
Before: …
=> Use black navigation bar in black AMOLED theme

app/src/main/java/com/mxt/anitrend/base/custom/pager/BaseStatePageAdapter.java
See: https://github.com/AniTrend/anitrend-app/issues/483
See: https://github.com/AniTrend/anitrend-app/issues/483
Set your phone to Dutch, then set app language to anything but Dutch, notice that ViewPager titles are now correct.
n/a
**IMPORTANT**: By submitting a patch, …
=> Use user specified Locale in BaseStatePageAdapter::setPagerTitles()

app/src/main/java/com/mxt/anitrend/util/NotificationUtil.kt
This is required since we target Android 12+ API:
https://developer.android.com/guide/components/intents-filters#DeclareMutabilityPendingIntent
See #489
Compile tested.
n/a
owners to license your work …
=> Use PendingIntent.FLAG_IMMUTABLE flag for our intents

app/src/main/AndroidManifest.xml
POST_NOTIFICATIONS permission is required for posting notifications on Android T.
Notifications weren't working for me ;(
Now I can turn on notifications again.
n/a
owners to license your work under the …
=> Grant android.permission.POST_NOTIFICATIONS

app/.meta/version.json, app/src/main/assets/changelog.md, buildSrc/src/main/java/com/mxt/anitrend/buildsrc/common/Configuration.kt
=> Bump version from [1.9.11 to 1.9.12]

app/src/main/java/com/mxt/anitrend/adapter/pager/index/TrendingPageAdapter.java, app/src/main/res/values-ar/string_array_items.xml, app/src/main/res/values-de/string_array_items.xml, app/src/main/res/values-es/string_array_items.xml, app/src/main/res/values-fr/string_array_items.xml, app/src/main/res/values-it/string_array_items.xml, app/src/main/res/values-nl/string_array_items.xml, app/src/main/res/values-pl/string_array_items.xml, app/src/main/res/values-pt/string_array_items.xml, app/src/main/res/values-sv/string_array_items.xml, app/src/main/res/values/string_array_items.xml, app/src/main/res/values/string_arrays.xml
This basically renames existing "BEING WATCHED" tab to "TRENDING ANIME", and adds "TRENDING MANGA" next to it.
See https://github.com/AniTrend/anitrend-app/issues/512
Open "What's Trending", swipe right.
**IMPORTANT**: By submitting a patch, you agree to allow the …
=> Add "TRENDING MANGA" tab to What's Trending page

app/src/main/java/com/mxt/anitrend/util/NotificationUtil.kt
=> Add remaining media related keys to notification builder

app/.meta/version.json, gradle/version.properties
=> automation: update version.properties

.github/scripts/setup-config.sh, .github/workflows/android-unit-test-release.yaml, .github/workflows/android-unit-test.yaml, .github/workflows/version-updater.yml
=> chore: add config script for project setup

.idea/gradle.xml, .idea/kotlinc.xml, buildSrc/src/main/java/com/mxt/anitrend/buildsrc/components/AndroidComponents.kt, gradle/libs.versions.toml
=> chore: fix failing build due to lint and deps

.github/workflows/android-build.yaml
=> chore: add new action for managing assets uploads

.idea/gradle.xml, .idea/kotlinc.xml, app/src/main/java/com/mxt/anitrend/extension/ContextExt.kt, app/src/main/java/com/mxt/anitrend/util/NotificationUtil.kt, app/src/main/java/com/mxt/anitrend/view/activity/index/MainActivity.kt
=> chore: add notification permission check

app/src/github/java/com/mxt/anitrend/base/custom/activity/ActivityDelegateExtensions.kt, app/src/github/java/com/mxt/anitrend/service/DownloaderService.kt
=> hotfix: simplify storage management for in-app updates

app/src/main/assets/graphql/queries/feed/FeedList.graphql
=> hotfix: resolve feed list not return results for following progress

app/src/main/java/com/mxt/anitrend/base/plugin/image/GlideImagePlugin.kt, app/src/main/java/com/mxt/anitrend/koin/Modules.kt
=> refactor: use system browser user agent for glide by default

.github/workflows/android-build.yaml, Gemfile.lock, fastlane/Fastfile, fastlane/metadata/android/en-GB/changelogs/default.txt, fastlane/metadata/android/en-GB/full_description.txt, fastlane/metadata/android/en-GB/short_description.txt
=> build: update fastlane and workflow
